mixed-port: 7890

external-controller: 127.0.0.1:9090
allow-lan: false
mode: global
log-level: warning

proxies:
  - { name: 'dmit.xinsi.us', type: trojan, server: dmit.xinsi.us, port: 444, password: chen4753317, xtls: true}
  - {name: 'Bj', type: ss, server: activity.huawei.daanyht.com, port: 12604, cipher: aes-128-gcm, password: haMLMXirByn6rGVh, plugin: obfs, plugin-opts: {mode: http, host: feacdd9f5aae.microsoft.com}}  
  - { name: 'hk-dmit.xinsi.us', type: trojan, server: hk-dmit.xinsi.us, port: 443, password: chen4753317, xtls: true}
  - { name: 'dmit-san.xinsi.us', type: trojan, server: dmit.xinsi.us, port: 54000, password: chen4753317, xtls: true, skip-cert-verify: true }
  - { name: 'san.xinsi.us', type: trojan, server: san.xinsi.us, port: 443, password: chen4753317, xtls: true }
  - { name: 'asb.xinsi.us', type: trojan, server: asb.xinsi.us, port: 443, password: chen4753317, xtls: true }
  - { name: 'san-forward.xinsi.us', type: trojan, server: dsan.xinsi.us, port: 65000, password: chen4753317, xtls: true, skip-cert-verify: true }
  - { name: 'tr.xinsi.us', type: trojan, server: tr.xinsi.us, port: 443, password: chen4753317, xtls: true, skip-cert-verify: true}
  - { name: 'tokyo.xinsi.us', type: trojan, server: tokyo.xinsi.us, port: 443, password: Carlosx0514!, xtls: true}
  - { name: 'san-tokyo.xinsi.us', type: trojan, server: tokyo.xinsi.us, port: 65000, password: chen4753317, xtls: true, skip-cert-verify: true}
  - { name: 'osaka.xinsi.us', type: trojan, server: jp.xinsi.us, port: 443, password: chen4753317, xtls: true}
  - { name: 'sg1.xinsi.us', type: trojan, server: sg1.xinsi.us, port: 443, password: chen4753317, xtls: true}
  - { name: 'san-sg.xinsi.us', type: trojan, server: sg1.xinsi.us, port: 65000, password: chen4753317, xtls: true, skip-cert-verify: true }
  - { name: 'san-seoul.xinsi.us', type: trojan, server: seoul.xinsi.us, port: 65000, password: chen4753317, xtls: true, skip-cert-verify: true }
  - { name: 'asb-seoul.xinsi.us', type: trojan, server: seoul.xinsi.us, port: 64000, password: chen4753317, xtls: true, skip-cert-verify: true }
  - { name: 'seoul.xinsi.us', type: trojan, server: seoul.xinsi.us, port: 443, password: chen4753317, xtls: true }
  - { name: 'de.xinsi.us', type: trojan, server: sg1.xinsi.us, port: 63000, password: chen4753317, xtls: true, skip-cert-verify: true}
  - { name: 'tr-sg1.xinsi.us', type: trojan, server: sg1.xinsi.us, port: 64000, password: chen4753317, xtls: true, skip-cert-verify: true}
  
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - dmit.xinsi.us
      - san.xinsi.us
      - asb.xinsi.us
      - tr.xinsi.us
      - sg1.xinsi.us
      - dmit-san.xinsi.us
      - tr-sg1.xinsi.us  
      
  - name: SG
    type: select
    proxies:
      - sg1.xinsi.us     

rules:
  - DOMAIN-KEYWORD,amazon,Proxy
  - DOMAIN-KEYWORD,google,Proxy
  - DOMAIN-KEYWORD,gmail,Proxy
  - DOMAIN-KEYWORD,youtube,Proxy
  - DOMAIN-KEYWORD,facebook,Proxy
  - DOMAIN-SUFFIX,fb.me,Proxy
  - DOMAIN-SUFFIX,fbcdn.net,Proxy
  - DOMAIN-KEYWORD,twitter,Proxy
  - DOMAIN-KEYWORD,instagram,Proxy
  - DOMAIN-KEYWORD,dropbox,Proxy
  - DOMAIN-SUFFIX,twimg.com,Proxy
  - DOMAIN-KEYWORD,blogspot,Proxy
  - DOMAIN-SUFFIX,youtu.be,Proxy
  - DOMAIN-KEYWORD,whatsapp,Proxy

# 常见广告域名屏蔽
  - DOMAIN-KEYWORD,admarvel,REJECT
  - DOMAIN-KEYWORD,admaster,REJECT
  - DOMAIN-KEYWORD,adsage,REJECT
  - DOMAIN-KEYWORD,adsmogo,REJECT
  - DOMAIN-KEYWORD,adsrvmedia,REJECT
  - DOMAIN-KEYWORD,adwords,REJECT
  - DOMAIN-KEYWORD,adservice,REJECT
  - DOMAIN-KEYWORD,domob,REJECT
  - DOMAIN-KEYWORD,duomeng,REJECT
  - DOMAIN-KEYWORD,dwtrack,REJECT
  - DOMAIN-KEYWORD,guanggao,REJECT
  - DOMAIN-KEYWORD,lianmeng,REJECT
  - DOMAIN-SUFFIX,mmstat.com,REJECT
  - DOMAIN-KEYWORD,omgmta,REJECT
  - DOMAIN-KEYWORD,openx,REJECT
  - DOMAIN-KEYWORD,partnerad,REJECT
  - DOMAIN-KEYWORD,pingfore,REJECT
  - DOMAIN-KEYWORD,supersonicads,REJECT
  - DOMAIN-KEYWORD,uedas,REJECT
  - DOMAIN-KEYWORD,umeng,REJECT
  - DOMAIN-KEYWORD,usage,REJECT
  - DOMAIN-KEYWORD,wlmonitor,REJECT
  - DOMAIN-KEYWORD,zjtoolbar,REJECT
  
# Netflix

  - DOMAIN,e13252.dscg.akamaiedge.net,Proxy
  - DOMAIN,h-netflix.online-metrix.net,Proxy
  - DOMAIN,netflix.com.edgesuite.net,Proxy
  - DOMAIN-SUFFIX,fast.com,Proxy
  - DOMAIN-SUFFIX,flxvpn.net,Proxy
  - DOMAIN-SUFFIX,netflix.ca,Proxy
  - DOMAIN-SUFFIX,netflix.com,Proxy
  - DOMAIN-SUFFIX,netflix.com.au,Proxy
  - DOMAIN-SUFFIX,netflix.com.edgesuite.net,Proxy
  - DOMAIN-SUFFIX,netflix.net,Proxy
  - DOMAIN-SUFFIX,netflixdnstest0.com,Proxy
  - DOMAIN-SUFFIX,netflixdnstest1.com,Proxy
  - DOMAIN-SUFFIX,netflixdnstest10.com,Proxy
  - DOMAIN-SUFFIX,netflixdnstest2.com,Proxy
  - DOMAIN-SUFFIX,netflixdnstest3.com,Proxy
  - DOMAIN-SUFFIX,netflixdnstest4.com,Proxy
  - DOMAIN-SUFFIX,netflixdnstest5.com,Proxy
  - DOMAIN-SUFFIX,netflixdnstest6.com,Proxy
  - DOMAIN-SUFFIX,netflixdnstest7.com,Proxy
  - DOMAIN-SUFFIX,netflixdnstest8.com,Proxy
  - DOMAIN-SUFFIX,netflixdnstest9.com,Proxy
  - DOMAIN-SUFFIX,netflixinvestor.com,Proxy
  - DOMAIN-SUFFIX,netflixstudios.com,Proxy
  - DOMAIN-SUFFIX,netflixtechblog.com,Proxy
  - DOMAIN-SUFFIX,nflxext.com,Proxy
  - DOMAIN-SUFFIX,nflximg.com,Proxy
  - DOMAIN-SUFFIX,nflximg.net,Proxy
  - DOMAIN-SUFFIX,nflxsearch.net,Proxy
  - DOMAIN-SUFFIX,nflxso.net,Proxy
  - DOMAIN-SUFFIX,nflxvideo.net,Proxy
  - DOMAIN-SUFFIX,us-west-2.amazonaws.com,Proxy
  - DOMAIN-KEYWORD,apiproxy-device-prod-nlb-,Proxy
  - DOMAIN-KEYWORD,dualstack.apiproxy-,Proxy
  - DOMAIN-KEYWORD,dualstack.ichnaea-web-,Proxy
  - DOMAIN-KEYWORD,netflixdnstest,Proxy
  - IP-CIDR,103.87.204.0/22,Proxy
  - IP-CIDR,107.23.255.0/26,Proxy
  - IP-CIDR,108.128.160.0/23,Proxy
  - IP-CIDR,108.128.162.0/24,Proxy
  - IP-CIDR,108.136.154.16/28,Proxy
  - IP-CIDR,108.136.154.32/27,Proxy
  - IP-CIDR,108.137.114.0/28,Proxy
  - IP-CIDR,108.137.114.64/26,Proxy
  - IP-CIDR,108.175.32.0/20,Proxy
  - IP-CIDR,13.112.191.184/29,Proxy
  - IP-CIDR,13.113.196.64/26,Proxy
  - IP-CIDR,13.113.203.0/24,Proxy
  - IP-CIDR,13.124.145.16/28,Proxy
  - IP-CIDR,13.124.145.64/26,Proxy
  - IP-CIDR,13.124.199.0/24,Proxy
  - IP-CIDR,13.124.247.0/24,Proxy
  - IP-CIDR,13.126.23.136/29,Proxy
  - IP-CIDR,13.126.23.144/28,Proxy
  - IP-CIDR,13.126.23.160/27,Proxy
  - IP-CIDR,13.126.23.192/27,Proxy
  - IP-CIDR,13.126.243.0/24,Proxy
  - IP-CIDR,13.127.70.128/27,Proxy
  - IP-CIDR,13.127.70.160/29,Proxy
  - IP-CIDR,13.208.131.0/27,Proxy
  - IP-CIDR,13.208.131.128/26,Proxy
  - IP-CIDR,13.208.131.192/27,Proxy
  - IP-CIDR,13.208.131.224/29,Proxy
  - IP-CIDR,13.208.131.232/30,Proxy
  - IP-CIDR,13.208.131.32/28,Proxy
  - IP-CIDR,13.208.177.224/27,Proxy
  - IP-CIDR,13.208.180.0/24,Proxy
  - IP-CIDR,13.208.194.0/23,Proxy
  - IP-CIDR,13.208.217.64/26,Proxy
  - IP-CIDR,13.208.227.0/24,Proxy
  - IP-CIDR,13.208.228.0/25,Proxy
  - IP-CIDR,13.208.228.128/29,Proxy
  - IP-CIDR,13.208.228.136/30,Proxy
  - IP-CIDR,13.208.33.16/28,Proxy
  - IP-CIDR,13.208.33.8/29,Proxy
  - IP-CIDR,13.209.1.0/28,Proxy
  - IP-CIDR,13.209.1.56/29,Proxy
  - IP-CIDR,13.209.1.96/27,Proxy
  - IP-CIDR,13.209.71.128/27,Proxy
  - IP-CIDR,13.209.71.224/27,Proxy
  - IP-CIDR,13.210.2.192/26,Proxy
  - IP-CIDR,13.210.67.128/26,Proxy
  - IP-CIDR,13.211.12.160/27,Proxy
  - IP-CIDR,13.211.12.192/27,Proxy
  - IP-CIDR,13.211.12.248/29,Proxy
  - IP-CIDR,13.211.166.192/28,Proxy
  - IP-CIDR,13.212.132.0/22,Proxy
  - IP-CIDR,13.212.209.128/26,Proxy
  - IP-CIDR,13.212.209.94/31,Proxy
  - IP-CIDR,13.212.209.96/27,Proxy
  - IP-CIDR,13.213.20.132/30,Proxy
  - IP-CIDR,13.213.20.136/29,Proxy
  - IP-CIDR,13.213.20.144/28,Proxy
  - IP-CIDR,13.213.20.160/28,Proxy
  - IP-CIDR,13.213.21.0/24,Proxy
  - IP-CIDR,13.213.22.0/23,Proxy
  - IP-CIDR,13.213.24.0/23,Proxy
  - IP-CIDR,13.213.75.224/29,Proxy
  - IP-CIDR,13.214.224.0/23,Proxy
  - IP-CIDR,13.214.228.0/22,Proxy
  - IP-CIDR,13.215.92.0/24,Proxy
  - IP-CIDR,13.215.93.0/25,Proxy
  - IP-CIDR,13.215.93.128/26,Proxy
  - IP-CIDR,13.225.176.0/21,Proxy
  - IP-CIDR,13.227.228.0/24,Proxy
  - IP-CIDR,13.228.69.0/24,Proxy
  - IP-CIDR,13.229.187.192/27,Proxy
  - IP-CIDR,13.229.187.232/29,Proxy
  - IP-CIDR,13.230.21.128/26,Proxy
  - IP-CIDR,13.230.21.224/27,Proxy
  - IP-CIDR,13.231.6.104/29,Proxy
  - IP-CIDR,13.231.6.112/28,Proxy
  - IP-CIDR,13.231.6.192/28,Proxy
  - IP-CIDR,13.231.6.208/29,Proxy
  - IP-CIDR,13.231.6.64/27,Proxy
  - IP-CIDR,13.232.67.128/26,Proxy
  - IP-CIDR,13.233.177.0/29,Proxy
  - IP-CIDR,13.233.177.192/26,Proxy
  - IP-CIDR,13.233.177.32/27,Proxy
  - IP-CIDR,13.234.221.136/29,Proxy
  - IP-CIDR,13.235.197.96/27,Proxy
  - IP-CIDR,13.235.228.0/24,Proxy
  - IP-CIDR,13.235.6.0/23,Proxy
  - IP-CIDR,13.236.8.0/25,Proxy
  - IP-CIDR,13.236.82.128/27,Proxy
  - IP-CIDR,13.236.82.96/27,Proxy
  - IP-CIDR,13.239.158.0/29,Proxy
  - IP-CIDR,13.244.121.196/30,Proxy
  - IP-CIDR,13.244.132.0/23,Proxy
  - IP-CIDR,13.244.202.40/29,Proxy
  - IP-CIDR,13.244.244.192/26,Proxy
  - IP-CIDR,13.244.33.0/25,Proxy
  - IP-CIDR,13.244.33.128/26,Proxy
  - IP-CIDR,13.245.1.32/27,Proxy
  - IP-CIDR,13.245.112.0/23,Proxy
  - IP-CIDR,13.245.114.0/24,Proxy
  - IP-CIDR,13.245.127.232/30,Proxy
  - IP-CIDR,13.245.155.128/27,Proxy
  - IP-CIDR,13.245.155.224/27,Proxy
  - IP-CIDR,13.245.166.128/29,Proxy
  - IP-CIDR,13.245.166.176/29,Proxy
  - IP-CIDR,13.245.93.140/30,Proxy
  - IP-CIDR,13.245.93.160/29,Proxy
  - IP-CIDR,13.245.93.176/28,Proxy
  - IP-CIDR,13.245.93.192/28,Proxy
  - IP-CIDR,13.246.108.0/22,Proxy
  - IP-CIDR,13.246.120.0/22,Proxy
  - IP-CIDR,13.246.70.0/23,Proxy
  - IP-CIDR,13.248.224.0/21,Proxy
  - IP-CIDR,13.248.232.0/23,Proxy
  - IP-CIDR,13.250.186.0/28,Proxy
  - IP-CIDR,13.250.186.128/26,Proxy
  - IP-CIDR,13.250.186.16/29,Proxy
  - IP-CIDR,13.250.186.192/28,Proxy  

# Capital One
  - DOMAIN-SUFFIX,capitalone.com,DIRECT
# Binance  
  - DOMAIN-KEYWORD,binance,SG
# LAN
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,17.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT

# 最终规则
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
